- name: "Check Cowsay Status"
  tags: status
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if cowsay executable in in PATH
      command: "which cowsay"
      register: result
      failed_when: false
      changed_when: false

    - name: Signal status installed
      debug:
        msg: 'ANSIBLE_SELF_SERVICE_STATUS_INSTALLED'
      when: result.rc == 0

    - name: Signal status not installed
      debug:
        msg: 'ANSIBLE_SELF_SERVICE_STATUS_NOT_INSTALLED'
      when: result.rc != 0

- name: "Install Cowsay"
  tags: install
  hosts: localhost
  gather_facts: no
  become: true
  roles:
    - cowsay
